repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  # rev: v4.4.0
  rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: forbid-submodules
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/shellcheck-py/shellcheck-py
  # rev: v0.9.0.2
  rev: 4bb61ddc1b4175565f8f975fd20d657f00f2bd53
  hooks:
  - id: shellcheck
- repo: https://github.com/pycqa/isort
  # rev: 5.11.4
  rev: 98390f5fde8f904f16a4e290a2aabed80d0951dc
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  # rev: 22.12.0
  rev: 2ddea293a88919650266472186620a98a4a8bb37
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  # rev: v0.991
  rev: 0b037c2b59aa62dc3be3287d175295f1a5547eb9
  hooks:
  - id: mypy
    additional_dependencies:
    - 'types-python-dateutil==2.8.19.5'
- repo: https://github.com/PyCQA/flake8
  # rev: 6.0.0
  rev: b9a7794c4f425ef8419081e6993f99419cc667ea
  hooks:
  - id: flake8
    additional_dependencies:
    - 'flake8-bugbear==23.1.14'
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  # rev: v1.3.1
  rev: a4a1eb373d8e809534a46855a58be427a0a29219
  hooks:
  - id: python-safety-dependencies-check
    args:
    - '--disable-telemetry'
- repo: https://github.com/antonbabenko/pre-commit-terraform
  # rev: v1.77.0
  rev: 1d54ea2b9950097568c6a7a2e2bcb6d4b4ebfb61
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
    args:
    - '--args=--module'
  - id: terraform_tfsec
  - id: terraform_validate
  - id: terraform_checkov
    args:
    - '--args=--quiet'
  - id: terrascan
    files: ^terraform/
