repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  # rev: v4.4.0
  rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: forbid-submodules
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/shellcheck-py/shellcheck-py
  # rev: v0.9.0.2
  rev: 4bb61ddc1b4175565f8f975fd20d657f00f2bd53
  hooks:
  - id: shellcheck
- repo: https://github.com/pycqa/isort
  # rev: 5.12.0
  rev: e44834b7b294701f596c9118d6c370f86671a50d
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  # rev: 23.1.0
  rev: b0d1fba7ac3be53c71fb0d3211d911e629f8aecb
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  # rev: v1.1.1
  rev: b176ead5d5b92b1d4e651c118017f8fd32de424a
  hooks:
  - id: mypy
    additional_dependencies:
    - 'types-python-dateutil==2.8.19.5'
- repo: https://github.com/PyCQA/flake8
  # rev: 6.0.0
  rev: b9a7794c4f425ef8419081e6993f99419cc667ea
  hooks:
  - id: flake8
    additional_dependencies:
    - 'flake8-bugbear==23.1.14'
- repo: https://github.com/PyCQA/bandit
  # rev: 1.7.5
  rev: ca4faf2f82a7c68a088100f8ba2b8e56f9bdcfe3
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml"]
    additional_dependencies: ["bandit[toml]"]
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  # rev: v1.3.1
  rev: a4a1eb373d8e809534a46855a58be427a0a29219
  hooks:
  - id: python-safety-dependencies-check
    args:
    - '--disable-telemetry'
- repo: https://github.com/antonbabenko/pre-commit-terraform
  # rev: v1.77.1
  rev: 7fb95618a952c1b4e86f35ee9103d3a67a86df0d
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
    args:
    - '--args=--module'
  - id: terraform_tfsec
  - id: terraform_validate
  - id: terraform_checkov
    args:
    - '--args=--quiet'
