version: "3.9"

services:
  web:
    container_name: web_container
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
      target: prod-env
    environment:
      APP_KEY: ${APP_KEY:-changeme}
      ADMIN_PASS: ${ADMIN_PASS:-changeme}
      DB_PASS: ${DB_PASS:-changeme}
    ports:
      - '8000:8000'
    links:
      - "postgres:database"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres_container
    image: "postgres:15.1-alpine3.17"
    user: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-changeme}
      POSTGRES_DB: sensors
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    postgres:
