name: Validate terraform code in pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - .github/workflows/pr-validate-terraform-code.yml
      - .terraform-version
      - .tflint-version
      - terraform/**

permissions: read-all

jobs:
  tflint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get tflint version
        run: |
          export VERSION=$(cat .tflint-version)
          echo "TFLINT_VERSION=$VERSION" >> $GITHUB_ENV
      - name: tflint
        uses: reviewdog/action-tflint@v1.17.2
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: "terraform"
          reporter: github-pr-review
          fail_on_error: "true"
          filter_mode: "nofilter"
          tflint_version: ${{ env.TFLINT_VERSION }}
          flags: "--module"

  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.29.1
        with:
          path: terraform

  terraform-plan-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create config files
        run: |
          cat > config.tfbackend << EOL
            ${{ secrets.CONFIG_TFBACKEND_DEV }}
          EOL
          cat > config.tfvars << EOL
            ${{ secrets.CONFIG_TFVARS_DEV }}
            repository="${{ github.repository }}"
          EOL
      - name: terraform validate
        uses: dflook/terraform-validate@v1.29.1
        with:
          path: terraform/envs/dev
          backend_config_file: config.tfbackend
      - name: terraform plan
        uses: dflook/terraform-plan@v1.29.1
        with:
          path: terraform/envs/dev
          backend_config_file: config.tfbackend
          var_file: config.tfvars

  terraform-plan-prod:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create config files
        run: |
          cat > config.tfbackend << EOL
            ${{ secrets.CONFIG_TFBACKEND_PROD }}
          EOL
          cat > config.tfvars << EOL
            ${{ secrets.CONFIG_TFVARS_PROD }}
            repository="${{ github.repository }}"
          EOL
      - name: terraform validate
        uses: dflook/terraform-validate@v1.29.1
        with:
          path: terraform/envs/prod
          backend_config_file: config.tfbackend
      - name: terraform plan
        uses: dflook/terraform-plan@v1.29.1
        with:
          path: terraform/envs/prod
          backend_config_file: config.tfbackend
          var_file: config.tfvars
