name: Release and deploy changes
concurrency: release
on:
  push:
    branches:
      - main

jobs:
  terraform-apply-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create config files
        run: |
          cat > config.tfbackend << EOL
            ${{ secrets.CONFIG_TFBACKEND_DEV }}
          EOL
          cat > config.tfvars << EOL
            ${{ secrets.CONFIG_TFVARS_DEV }}
            repository="${{ github.repository }}"
          EOL
      - name: terraform apply
        uses: dflook/terraform-apply@v1.29.1
        with:
          path: terraform/envs/dev
          backend_config_file: config.tfbackend
          var_file: config.tfvars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform-destroy-dev:
    runs-on: ubuntu-latest
    needs:
      - terraform-apply-dev
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create config files
        run: |
          cat > config.tfbackend << EOL
            ${{ secrets.CONFIG_TFBACKEND_DEV }}
          EOL
          cat > config.tfvars << EOL
            ${{ secrets.CONFIG_TFVARS_DEV }}
            repository="${{ github.repository }}"
          EOL
      - name: terraform destroy
        uses: dflook/terraform-destroy@v1.29.1
        with:
          path: terraform/envs/dev
          backend_config_file: config.tfbackend
          var_file: config.tfvars

  terraform-apply-prod:
    runs-on: ubuntu-latest
    needs:
      - terraform-apply-dev
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create config files
        run: |
          cat > config.tfbackend << EOL
            ${{ secrets.CONFIG_TFBACKEND_PROD }}
          EOL
          cat > config.tfvars << EOL
            ${{ secrets.CONFIG_TFVARS_PROD }}
            repository="${{ github.repository }}"
          EOL
      - name: terraform apply
        uses: dflook/terraform-apply@v1.29.1
        with:
          path: terraform/envs/prod
          backend_config_file: config.tfbackend
          var_file: config.tfvars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
